### ISSUE TITLE
the partVolume.cfg is not created

### ISSUE THREAD

**Issue by snakeru** [linuxgurugamer/KSP_PartVolume#1]
The log file has lines like this one:
System.TypeLoadException: Could not load type of field 'KSP_PartVolume.PartVolume:Log' (1) due to: Could not load file or assembly 'KSP_Log, Version=0.1.1.6, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:KSP_Log, Version=0.1.1.6, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>

My understanding is that this corresponds to the first run, however once I exit the game the config file is not created either so the next run repeats the first.

OS: linux
GameData contents:
000_AT_Utils  CommunityCategoryKit   GroundConstruction       ModuleManager.ConfigCache  ModuleManager.TechTree
000_USITools  CommunityResourcePack  KSP_PartVolume           ModuleManager.ConfigSHA    Squad
AutoLoadGame  Firespitter            ModuleManager.4.1.4.dll  ModuleManager.Physics      UmbraSpaceIndustries

**Comment by linuxgurugamer** [comment]
Do you have the dependencies loaded?  That message tells me that the SpaceTuxLibrary isn't installed,
How did you install it, via CKAN or manually?

**Comment by snakeru** [comment]
I installed KSP_PartVolume by hand: looked into the zip, found the readme, looked for dependencies. None were listed. Thank you for the tip! I now installed these:
000_ClickThroughBlocker
001_ToolbarControl
SpaceTuxLibrary

And it worked. Thanks! Would you like me sending you a PR with updated README?

**Comment by linuxgurugamer** [comment]
If you want, but the forum and CKAN are really the best places to get info on mods
