### ISSUE TITLE
ModuleGroundPart not blacklisted

### ISSUE THREAD

**Issue by Rodg88** [linuxgurugamer/KSP_PartVolume#10]
Parts with `ModuleGroundPart` aren't skipped, causing the part to have two different volumes defined at once.

Happens for some surface experiment parts in BDB, which use regular science modules instead of `ModuleGroundExperiment`, but I'll also just add the parts in question to the manual blacklist.

**Comment by linuxgurugamer** [comment]
I wasn't aware of that, I'll update the mod with that as an exclusion

**Comment by linuxgurugamer** [comment]
Thank you for the report
Fixed and updated
