### ISSUE TITLE
Interaction with KSP Community Fixes causes some parts to have -1 volume

### ISSUE THREAD

**Issue by Rodg88** [linuxgurugamer/KSP_PartVolume#11]
Installing both PartVolume and [KSP Community Fixes ](https://github.com/KSPModdingLibs/KSPCommunityFixes/releases) seems to cause parts that should be skipped or blacklisted to be set to -1 volume, and these parts are still storable, just deducting 1 from the stored volume. 

It at least happens to the stock deployable science parts. Removing either mod (while keeping the PV config file) prevents the issue.

**Comment by Rodg88** [comment]
https://forum.kerbalspaceprogram.com/topic/122020-1125-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v1130-%D0%B7%D0%B0%D0%B1%D1%8B%D1%82%D1%8B%D0%B9-13aug2023/?do=findComment&comment=4410096

Link to a user report with log

**Comment by linuxgurugamer** [comment]
Would be nice if you were a bit more specific, as in which parts, which mods, etc

**Comment by linuxgurugamer** [comment]
I found the problem, will have an update out soon

**Comment by linuxgurugamer** [comment]
FYI:  It had nothing to do with the KSP Community Fixes

**Comment by Rodg88** [comment]
Still experiencing it, and recreated it with the following:
Stock+DLC, KSP_PartVolume 0.3.12 (plus ClickThroughBlocker, ToolbarControl, SpaceTuxLibrary), KSPCommunityFixes 1.35.2 (plus Harmony), and MM.

Launch the game, go to the VAB, place a stock SEQ-3 cargo container, then pick a stock deployable science part, like `DeployedGoExOb` and place it in the cargo container's inventory. The volume used will be correct whole holding the part over an inv slot, but when placed it'll end up being -1L.

https://github.com/user-attachments/assets/605fad3b-5c99-4826-987d-280d973a4166

[negativevolumelogs.zip](https://github.com/user-attachments/files/16376780/negativevolumelogs.zip)

Removing KSPCF prevents it from happening

**Comment by linuxgurugamer** [comment]
Looks like I have to add the ModuleGroundExperiment to an ignore list, working on it

**Comment by linuxgurugamer** [comment]
ModuleGroundPart was from Bluedog, which is what I fixed originally.  This new report is for stock parts, so I've added all the parts with ModuleGround... to the exclusion list

So, for stock:

-  ModuleGroundCommsPart
-  ModuleGroundExpControl
-  ModuleGroundExperiment
-  ModuleGroundSciencePart

and for BlueDog:

- ModuleGroundPart

**Comment by linuxgurugamer** [comment]
Update complete
