### ISSUE TITLE
DIV0 in KSP_PartVolume.PartVolume.Start()

### ISSUE THREAD

**Issue by dtrauma** [linuxgurugamer/KSP_PartVolume#6]
Besides fairly standard (and popular) mods, most of them changing UI/VFX/behaviour and not adding parts, I have some old parts lying around, some of them probably need some love. At any rate the dll commits suicide in my install:

```
Uploading Crash Report
DivideByZeroException: Attempted to divide by zero.
  at KSP_PartVolume.PartVolume.Start () [0x00490] in <53145ed3064347dd9839cfbb7adf4b57>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
 
(Filename: <53145ed3064347dd9839cfbb7adf4b57> Line: 0)
```

**Comment by linuxgurugamer** [comment]
Ummm, as you say, it sound like really old parts which aren't compatible with current KSP.  At a guess, it doesn't have any mass.
Regardless, without knowing the part, I can't do anything, even if it was a bug, since I would have no way to test it

Also, I would need the complete Player.log, which would provide me some info which you don't have in the above snippet

**Comment by dtrauma** [comment]
> doesn't have any mass.

No, they're not _that_ broken :). I guess the models don't have proper hitboxes or something, so your mod ends up with a point volume.

I made a folder with anything I thought you might need, including the suspicious parts:
https://drive.google.com/drive/folders/1Sjx-nD9FgsM63M0nhU-VXLniLYFNi438?usp=sharing

As you can see, most mods are actually maintained by you :) (and a big thanks for all the work you do here).

If it takes too much of your time to look into this (and as long as it only affects me), I could absolutely live without this mod, as I'm mainly interested in making all parts EVA editable, not necessarily storable anyway, but I figured you probably wanted to know about this.

**Comment by linuxgurugamer** [comment]
The file "dubious-mods.zst" only contained an image file

**Comment by linuxgurugamer** [comment]
Is this the SurfaceAttachableControl mod from nesd that you are having problems with?

**Comment by linuxgurugamer** [comment]
Assuming that's the mod, it's not going to work because these parts don't have any real volume.
For now, add it to the PartBlacklist.cfg in the KSP_PartVolume folder, you can either add one line for each part, or try this:

blacklistRegexPattern = ^nesdCFH.*$

**Comment by linuxgurugamer** [comment]
Just an FYI, I just tested this with the SurfaceAttachableControl mod from nesd, didn't get an error, so would need to investigate this further.

**Comment by dtrauma** [comment]
Huh that's weird, just double checked and the archive works for me with two different archivers. I just uploaded it again, and uncompressed and the part folder of the single part I heavily suspect.

**Comment by dtrauma** [comment]
So I think I blacklisted the part and it apparently didn't help. I still get the DIV0. Attached blacklist so you can check if I did something wrong.

**Comment by linuxgurugamer** [comment]
I normally use 7Zip, also tried peazip
Could you redo it as a zip file, please?

**Comment by dtrauma** [comment]
It's a zstd tar, but as I said, I already uploaded a copy in umcompressed tar and plain files (you should see a "Parts" subdirectory).

**Comment by linuxgurugamer** [comment]
Got the tar file (missed that, sorry), and it's good

**Comment by linuxgurugamer** [comment]
Ok, so I've added both of the mods from your tar file to my test install, and no DIV0 errors happened

You are going to have to make a new install and try to isolate the minimum set of mods which cause the error, there is obviously some sort of mod interaction going on here, and I don't have time to figure that out.

Once you have a minimum set of mods, let me know and I can try to recreate it at that time.

FYI, the fact that the blacklist didn't work is interesting, not sure.  If you are sure it's those parts, you can try to put individual lines into the blacklist file, one for each part

**Comment by linuxgurugamer** [comment]
I took another look.  While I still don't know why, I did find one potential divide-by-zero, only in very odd circumstances.
It will be released as 0.0.3.6 later this evening

**Comment by linuxgurugamer** [comment]
Please let me know if this fixes your problem, if it does, can you close this?

**Comment by dtrauma** [comment]
Indeed, it works! Thank you.
