### ISSUE TITLE
"New parts detected" loop

### ISSUE THREAD

**Issue by WarrenSchultz** [linuxgurugamer/KSP_PartVolume#7]
I've tried switching on all the options except size limiting, and now the plugin detects new parts on each run of the game.

Is there a way to easily see a log of where it is detecting changes?

![image](https://user-images.githubusercontent.com/8450968/200069943-8023f116-abe8-44d5-a36e-af925eabf940.png)

**Comment by linuxgurugamer** [comment]
First, you should report things like this in the forums, not here.
Second, I would need the following:

Player.log
partVolumes-v3.cfg

In answer to your question, currently it doesn't say anything specific about new parts

Please follow up with this on the forums, I'll see what the files show when you post them there (links to them, that is)

**Comment by WarrenSchultz** [comment]
Well, eventually it went away, no specific changes made. Sorry to bother!
