### ISSUE TITLE
[BUG] logging uses [ERR

### ISSUE THREAD

**Issue by zer0Kerbal** [linuxgurugamer/KSP_PartVolume#8]
KSP_PartVolume logs its actions into KSP.log.
In doing so the game/plugin uses the [ERR flag; which makes sorting/filtering logs for real [ERR a headache.

e.g.
`KSP.log:8803:[ERR 01:28:20.877] KSP_PartVolume: Modified part: LunaticAeronautics/KerbalXMAS/Parts/xmas-candy-rcs-small/rcsCandysmall`

I use an automated script to filter for [ERR [EXC log lines (along with addon specific log messages) - KSP_PartVolume log entries should not be included in those lines - massively slows down what should be a simple several second review process.

Kindly change/fix the log output to something other that [ERR | [WRN | [EXC.

Mahalo!

Merry Christmas!

zed'K

**Comment by linuxgurugamer** [comment]
Most of what it logs are actually errors, I did find one line which it's writing out the following:
Modified part: .....
I'll change that and get a release out, but before I do, want to know if there are other messages you are seeing which are listed as error which aren't errors

**Comment by linuxgurugamer** [comment]
FYI, I use this:  https://textanalysistool.github.io/
which does a great job of only presenting what I want to see with filters.  It's extremely fast, and free to boot

**Comment by zer0Kerbal** [comment]
> other messages

thank you, no that is it.

thank you - use it from time to time. Also LogFusion when I need to dig in; but for the day-to-day I just use a simple batch FINDSTR > log.txt

Merry Christmas!
